## see genAction for list of names
/Compton/gun/mode comptonall

/Compton/gun/verbose 0
/Compton/run/runnumber 33
/Compton/run/autosave 100
/Compton/gun/ElectronEnergy 1.160 GeV
/Compton/gun/LaserWavelenght 532 nm

###this needs to be double checked - it should be ~6 m . is this going to matter for 1GeV?
#### the photon detector is placed 6 meteres DS of "0". 
/Compton/gun/PhotonVertexZ 0.0 mm


/Compton/gun/Initialize

/Compton/event/printevent 10

## cut for tracking optical photons
/Compton/step/OpticalMaxStepTime 250 ns

### do not store each event in the detector .. check if it's on or off
/Compton/detector/setoptions :ALL_IGNORE: store_edep_hits=no

/tracking/verbose 0
#/process/list
#/process/setVerbose 2 OpBoundary

/run/beamOn 1
