/Compton/gun/mode 3
/Compton/gun/verbose 0
/Compton/run/runnumber 29
/Compton/run/autosave 2
#/Compton/gun/ElectronEnergy 6.417 GeV
/Compton/gun/ElectronEnergy 0.95 GeV
#/Compton/gun/ElectronEnergy 3.4 GeV
#/Compton/gun/ElectronEnergy 10.617 GeV

### set to 1 if you want to get printouts for every step
######### this has a cin.ignore() statement in it so it will stop at every step
/Compton/step/verbose 0

### which hits do you want to store? 1: only primaries 2: everything but optical photons
/Compton/step/hitProcessLevel 1

/Compton/gun/LaserWavelenght 532 nm
#/Compton/gun/LaserWavelenght 1064 nm
#/Compton/gun/PhotonVertexZ 0.0 mm
/Compton/gun/PhotonVertexZ 500.0 mm
/Compton/gun/Initialize
/Compton/event/printevent 1
/Compton/step/OpticalMaxStepTime 250 ns
/Compton/detector/setoptions :ALL_IGNORE: store_edep_hits=no

/tracking/verbose 0
#/process/list
#/process/setVerbose 2 OpBoundary

/run/beamOn 100
