/Compton/gun/mode 5
/Compton/gun/verbose 0
/Compton/run/runnumber 141
/Compton/run/autosave 10000
/Compton/gun/ElectronEnergy 1.160 GeV
/Compton/gun/LaserWavelenght 532 nm
/Compton/gun/PhotonVertexZ 0.0 mm
/Compton/gun/TransversePol 0.0
/Compton/gun/Initialize
/Compton/event/printevent 250
/Compton/step/OpticalMaxStepTime 250 ns
/Compton/detector/setoptions :ALL_IGNORE: store_edep_hits=no
/Compton/geometry/initMagneticField DipoleField file_name=geometries/MagneticFieldDipole.dat

/tracking/verbose 0
#/process/list
#/process/setVerbose 2 OpBoundary

#/run/beamOn 1500
/run/beamOn 100
